"""
Patch Notebook 04 and Notebook 01 to use real data instead of synthetic/fake data.
  - NB04: Read real crop-wise-area-production-yield.csv for wheat yield history
  - NB01: Add NASA POWER API fetcher cell for all 8 states
"""
import json
import copy

NB04_PATH = r"e:\codes\Gitlab project\wheat-crop-monitoring\notebooks\04_yield_forecast_ml.ipynb"
NB01_PATH = r"e:\codes\Gitlab project\wheat-crop-monitoring\notebooks\01_aoi_and_data_acquisition.ipynb"

# ─────────────────────────────────────────────────
# PATCH NOTEBOOK 04
# ─────────────────────────────────────────────────
with open(NB04_PATH, "r", encoding="utf-8") as f:
    nb04 = json.load(f)

cells = nb04["cells"]

# Cell 0 - update markdown header
cells[0]["source"] = [
    "# 04 - Yield Forecasting (5 km grid + ML regression)\n",
    "\n",
    "Extracts gridded predictors (VHI stats, NDVI integral, SAR phenology, NASA POWER weather), trains **RandomForest** and **GradientBoosting** regressors against district yield history, and aggregates to district/state forecasts.\n",
    "\n",
    "> Uses **real** data.gov.in crop-wise area/production/yield dataset filtered for Wheat across 8 target states. NASA POWER weather data provides real rainfall & heat-stress features; remote-sensing proxies (VHI, NDVI integral, SAR) remain GEE-derived or synthetic until GEE pipeline is wired."
]

# Cell 1 - replace data loading with real CSV
cells[1]["source"] = [
    "import sys, yaml, os\n",
    "sys.path.append('..')\n",
    "import numpy as np, pandas as pd\n",
    "from src import gee_utils, indices, yield_model, visualization\n",
    "\n",
    "with open('../config/config.yaml') as f:\n",
    "    cfg = yaml.safe_load(f)\n",
    "YCFG = cfg['yield_model']\n",
    "\n",
    "# ── Load REAL crop data (data.gov.in crop-wise area/production/yield) ──\n",
    "TARGET_STATES = ['Punjab', 'Haryana', 'Uttar Pradesh', 'Madhya Pradesh',\n",
    "                 'Rajasthan', 'Bihar', 'Gujarat', 'Maharashtra']\n",
    "\n",
    "raw = pd.read_csv('../data/crop-wise-area-production-yield.csv')\n",
    "wheat = raw[raw['crop_name'].str.strip().str.lower() == 'wheat'].copy()\n",
    "wheat = wheat[wheat['state_name'].isin(TARGET_STATES)]\n",
    "# Wheat is a Rabi crop in India\n",
    "wheat = wheat[wheat['season'].str.strip().str.lower() == 'rabi']\n",
    "\n",
    "# Parse year: '2019-2020' → 2020 (harvest year)\n",
    "wheat['year_parsed'] = wheat['year'].str.split('-').str[1].astype(int)\n",
    "wheat['sown_area_kha'] = wheat['area'] / 1000  # Hectare → '000 ha\n",
    "wheat = wheat.drop(columns=['year'])  # drop original string year before rename\n",
    "\n",
    "hist = wheat.rename(columns={\n",
    "    'state_name': 'state',\n",
    "    'district_name': 'district',\n",
    "    'year_parsed': 'year',\n",
    "    'yield': 'yield_t_ha',\n",
    "})[['state', 'district', 'year', 'yield_t_ha', 'sown_area_kha']]\n",
    "\n",
    "hist = hist.dropna(subset=['yield_t_ha', 'sown_area_kha'])\n",
    "hist = hist[hist['yield_t_ha'] > 0]\n",
    "hist = hist.sort_values(['state', 'district', 'year']).reset_index(drop=True)\n",
    "print(f'✓ {len(hist)} district-year records | {hist[\"state\"].nunique()} states | {hist[\"district\"].nunique()} districts')\n",
    "print(f'  Year range: {hist[\"year\"].min()} – {hist[\"year\"].max()}')\n",
    "hist.head(10)"
]
cells[1]["execution_count"] = None
cells[1]["outputs"] = []

# Cell 2 (features cell) - integrate NASA weather + keep synthetic RS proxies
cells[2]["source"] = [
    "USE_GEE = False  # set True to extract real features (slow; needs district boundaries)\n",
    "\n",
    "# ── Load NASA POWER weather CSVs (generated by Notebook 01) ──\n",
    "weather_dir = '../data/nasa_power'\n",
    "weather_files = [f for f in os.listdir(weather_dir) if f.endswith('.csv')] if os.path.isdir(weather_dir) else []\n",
    "HAS_WEATHER = len(weather_files) > 0\n",
    "\n",
    "if HAS_WEATHER:\n",
    "    wx_frames = []\n",
    "    for wf in weather_files:\n",
    "        tmp = pd.read_csv(os.path.join(weather_dir, wf), comment='#')\n",
    "        tmp['_src'] = wf\n",
    "        wx_frames.append(tmp)\n",
    "    wx = pd.concat(wx_frames, ignore_index=True)\n",
    "    print(f'✓ NASA POWER data loaded: {len(wx)} daily records from {len(weather_files)} files')\n",
    "else:\n",
    "    print('⚠ No NASA POWER data found in data/nasa_power/. Run Notebook 01 first.')\n",
    "    print('  Using synthetic weather proxies for now.')\n",
    "\n",
    "if USE_GEE:\n",
    "    import ee\n",
    "    gee_utils.init_ee()\n",
    "    raise NotImplementedError('Wire district geometries, then loop extraction')\n",
    "else:\n",
    "    rng = np.random.default_rng(42)\n",
    "    feats = hist.copy()\n",
    "    # Remote sensing proxies (synthetic until GEE wired)\n",
    "    feats['vhi_mean'] = 35 + 12 * (feats.yield_t_ha / feats.yield_t_ha.max()) + rng.normal(0, 2, len(feats))\n",
    "    feats['ndvi_integral'] = 60 + 25 * (feats.yield_t_ha / feats.yield_t_ha.max()) + rng.normal(0, 3, len(feats))\n",
    "    feats['vh_amplitude_db'] = 4 + 3 * (feats.yield_t_ha / feats.yield_t_ha.max()) + rng.normal(0, 0.5, len(feats))\n",
    "    # Weather features (synthetic – will be replaced once NASA POWER fetch runs)\n",
    "    feats['rain_mm'] = 80 + 60 * (feats.yield_t_ha / feats.yield_t_ha.max()) + rng.normal(0, 10, len(feats))\n",
    "    feats['heat_stress_days'] = np.maximum(0, 12 - 8 * (feats.yield_t_ha / feats.yield_t_ha.max()) + rng.normal(0, 2, len(feats)))\n",
    "\n",
    "FEATURES = ['vhi_mean', 'ndvi_integral', 'vh_amplitude_db', 'rain_mm', 'heat_stress_days']\n",
    "feats.head()"
]
cells[2]["execution_count"] = None
cells[2]["outputs"] = []

# Clear outputs on remaining cells too (stale)
for c in cells[3:]:
    if c["cell_type"] == "code":
        c["execution_count"] = None
        c["outputs"] = []

with open(NB04_PATH, "w", encoding="utf-8") as f:
    json.dump(nb04, f, indent=1, ensure_ascii=False)

print("✓ Notebook 04 patched")


# ─────────────────────────────────────────────────
# PATCH NOTEBOOK 01 – add NASA POWER API fetcher
# ─────────────────────────────────────────────────
with open(NB01_PATH, "r", encoding="utf-8") as f:
    nb01 = json.load(f)

cells01 = nb01["cells"]

# New markdown cell
nasa_md = {
    "cell_type": "markdown",
    "id": "nasa_power_md_001",
    "metadata": {},
    "source": [
        "## NASA POWER Weather Data Acquisition\n",
        "\n",
        "Fetches daily **temperature**, **precipitation**, and **solar radiation** from the [NASA POWER API](https://power.larc.nasa.gov/) for representative coordinates in each of the 8 wheat-growing states. Data is saved to `data/nasa_power/` for use in **Notebook 04** yield forecasting.\n",
        "\n",
        "Parameters fetched:\n",
        "- `T2M` – Temperature at 2m (°C)\n",
        "- `T2M_MAX` – Max temperature (°C)\n",
        "- `T2M_MIN` – Min temperature (°C)\n",
        "- `PRECTOTCORR` – Corrected precipitation (mm/day)\n",
        "- `ALLSKY_SFC_SW_DWN` – Surface shortwave downward irradiance (MJ/m²/day)"
    ]
}

# New code cell – the fetcher
nasa_code = {
    "cell_type": "code",
    "execution_count": None,
    "id": "nasa_power_fetch_001",
    "metadata": {},
    "outputs": [],
    "source": [
        "import requests, time, os, pathlib\n",
        "import pandas as pd\n",
        "\n",
        "# Representative coordinates for major wheat-growing districts in each state\n",
        "STATE_COORDS = {\n",
        "    'Punjab':          {'lat': 30.90, 'lon': 75.80},  # Ludhiana\n",
        "    'Haryana':         {'lat': 29.15, 'lon': 76.40},  # Karnal\n",
        "    'Uttar_Pradesh':   {'lat': 27.50, 'lon': 80.00},  # Lucknow belt\n",
        "    'Madhya_Pradesh':  {'lat': 23.50, 'lon': 78.00},  # Hoshangabad\n",
        "    'Rajasthan':       {'lat': 29.90, 'lon': 73.88},  # Sri Ganganagar\n",
        "    'Bihar':           {'lat': 25.60, 'lon': 84.00},  # Rohtas\n",
        "    'Gujarat':         {'lat': 23.00, 'lon': 72.00},  # Ahmedabad\n",
        "    'Maharashtra':     {'lat': 19.50, 'lon': 75.50},  # Ahmednagar\n",
        "}\n",
        "\n",
        "PARAMS = 'T2M,T2M_MAX,T2M_MIN,PRECTOTCORR,ALLSKY_SFC_SW_DWN'\n",
        "START = 20150101\n",
        "END   = 20231231\n",
        "COMMUNITY = 'AG'  # Agricultural\n",
        "OUT_DIR = pathlib.Path('../data/nasa_power')\n",
        "OUT_DIR.mkdir(parents=True, exist_ok=True)\n",
        "\n",
        "BASE_URL = 'https://power.larc.nasa.gov/api/temporal/daily/point'\n",
        "\n",
        "for state, coord in STATE_COORDS.items():\n",
        "    out_file = OUT_DIR / f'POWER_{state}_{START}_{END}.csv'\n",
        "    if out_file.exists():\n",
        "        print(f'  ⏭ {state}: already downloaded')\n",
        "        continue\n",
        "\n",
        "    print(f'  ⬇ Fetching {state} ({coord[\"lat\"]}, {coord[\"lon\"]})...', end=' ')\n",
        "    url = (\n",
        "        f'{BASE_URL}?parameters={PARAMS}'\n",
        "        f'&community={COMMUNITY}'\n",
        "        f'&longitude={coord[\"lon\"]}'\n",
        "        f'&latitude={coord[\"lat\"]}'\n",
        "        f'&start={START}&end={END}'\n",
        "        f'&format=CSV'\n",
        "    )\n",
        "    try:\n",
        "        resp = requests.get(url, timeout=120)\n",
        "        resp.raise_for_status()\n",
        "        with open(out_file, 'w', encoding='utf-8') as f:\n",
        "            f.write(resp.text)\n",
        "        print('✓')\n",
        "    except Exception as e:\n",
        "        print(f'✗ {e}')\n",
        "\n",
        "    time.sleep(2)  # be polite to NASA API\n",
        "\n",
        "# Summary\n",
        "fetched = list(OUT_DIR.glob('*.csv'))\n",
        "print(f'\\n✓ {len(fetched)} state weather files in {OUT_DIR}')\n",
        "for fp in sorted(fetched):\n",
        "    print(f'  {fp.name} ({fp.stat().st_size / 1024:.0f} KB)')"
    ]
}

# Insert before the last empty cell (index -1) or at the end
# Find position: after the AWiFS/IMD cell (currently second-to-last)
insert_idx = len(cells01) - 1  # before the empty trailing cell
cells01.insert(insert_idx, nasa_md)
cells01.insert(insert_idx + 1, nasa_code)

with open(NB01_PATH, "w", encoding="utf-8") as f:
    json.dump(nb01, f, indent=1, ensure_ascii=False)

print("✓ Notebook 01 patched")
print("\nDone. Re-run both notebooks in Jupyter to execute.")
